---
# Playbook : acc.yml
# Author   : Ton Kersten
# Date     : 03-01-2019
#
# System wide playbook for the 'acc' environment

# Set all dynamic groups
- import_playbook: pre.yml
  tags: always

- name: run all playbooks, roles and tasks for 'acc'
  hosts: ansiblemanaged_True:&acc
  user: ansible
  become: True

  tasks:
    - name: acc | include "common" tasks
      import_tasks: tasks/common.yml
      tags: common

    - name: acc | include "ssh" tasks
      import_tasks: tasks/ssh.yml
      tags: [ ssh, openssh ]

    - name: acc | include "mysql" tasks
      import_tasks: tasks/mysql.yml
      when: "'mysql' in group_names"
      tags: mysql

    - name: acc | include "wiki" tasks
      import_tasks: tasks/wiki.yml
      when: "'wiki' in group_names"
      tags: wiki

- name: acc | show all hosts in environment 'acc' not managed by Ansible
  hosts: ansiblemanaged_False:&acc
  user: ansible
  become: True

  tasks:
    # Show all hosts not managed by Ansible
    - name: acc | include "managed hosts" tasks
      import_tasks: tasks/managed.yml

